server:
  port: 5002
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dlzz?useUnicode=true&characterEncoding=utf8
    username: root
    password: a19940129
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  config: classpath:log4j2-spring.xml