server:
  port: 8990
spring:
  datasource:
    db1:
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/dlzz?useUnicode=true&characterEncoding=utf8
      username: root
      password: a19940129
    db2:
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8
      username: root
      password: a19940129
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  config: classpath:log4j2-spring.xml