package com.example.dao.second;

import com.example.dao.seconddto.LogRecord;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface LogRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_record
     *
     * @mbg.generated
     */
    int insert(LogRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_record
     *
     * @mbg.generated
     */
    int insertSelective(LogRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_record
     *
     * @mbg.generated
     */
    LogRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LogRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LogRecord record);
}